In [2]:
x = 1
y = 2
x + y

3

In [3]:
x

1

In [4]:
def add_num(x, y):
    return x + y

add_num(1, 2)

3

In [6]:
def add_numbers(x, y, z=None):
  if z is None:
    return x+y
  else:
    return x + y + z

print(add_numbers(1, 2, 5))

8


In [7]:
def do_math(a, b, kind):
  if kind is None or kind=='add':
    return a+b
  else:
    return a-b

do_math(1, 2, None)

3

In [9]:
x = 'Dr. Christopher Brooks'

print(x[4:4+len('Christopher')])

Christopher


In [10]:
fullname = 'Christofer Arthur Hansen Brooks'
firstname = fullname.split()[0]
lastname = fullname.split()[-1]

In [11]:
print(firstname + ' ' + lastname)

Christofer Brooks


# CSV

In [12]:
import csv

In [13]:
%precision 2

'%.2f'

In [18]:
with open('resources/mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:3]

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [19]:
len(mpg)

234

In [20]:
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [21]:
sum(float(d['cty']) for d in mpg) / len(mpg)

16.86

In [22]:
sum(float(d['hwy']) for d in mpg) / len(mpg)

23.44

In [23]:
cylinders = set(d['cyl'] for d in mpg)

In [26]:
res = {}
for cyl in cylinders:
    cty_sum = 0.0
    cars = 0
    for d in mpg:
        if d['cyl'] == cyl:
            cty_sum += float(d['cty'])
            cars += 1
    res[cyl] = cty_sum / cars
print(res)

{'6': 16.21518987341772, '4': 21.012345679012345, '5': 20.5, '8': 12.571428571428571}


In [27]:
vehicle_classes = set(d['class'] for d in mpg)

In [28]:
veh_cls_hwy = {}
for cls in vehicle_classes:
    hwy_sum = 0.0
    cars = 0
    for d in mpg:
        if d['class'] == cls:
            hwy_sum += float(d['hwy'])
            cars += 1
    veh_cls_hwy[cls] = hwy_sum / cars
print(veh_cls_hwy)

{'suv': 18.129032258064516, 'minivan': 22.363636363636363, 'compact': 28.29787234042553, 'pickup': 16.87878787878788, 'subcompact': 28.142857142857142, 'midsize': 27.29268292682927, '2seater': 24.8}


# Time and Dates

In [29]:
import datetime as dt
import time as tm

In [30]:
tm.time()

1587238670.65

In [32]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2020, 4, 18, 21, 38, 39, 773269)

In [33]:
delta = dt.timedelta(days=100)
today = dt.date.today()
today - delta

datetime.date(2020, 1, 9)

In [34]:
today > today - delta

True

# Classes

In [35]:
class Person:
    department = 'School of Informatics'
    
    def set_name(self, name):
        self.name = name
    def set_location(self, location):
        self.location = location

In [39]:
person = Person()
person.set_name('Chris')
person.set_location('Ann Arbor')
person.age = 31  
# Person class has no attribute 'age', but this works. 
# You can misspell an existing attribute or just invent it out of thin air, Python does not protect you

In [40]:
print(person.department)
print(person.name)
print(person.location)
print(person.age)

School of Informatics
Chris
Ann Arbor
31


In [42]:
person2 = Person()
print(person2.age)
# However, if you call the same attribute from another class instance without explicit initialization, 
# you'll get an AttributeError.
# Python is awful for industrial programming!

AttributeError: 'Person' object has no attribute 'age'

# Map function

In [45]:
store1_prices = [10.00, 11.00, 12.34, 2.34]
store2_prices = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1_prices, store2_prices)
for price in cheapest:
    print(price)

9.0
11.0
12.34
2.01


In [47]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    tokens = person.split()
    return tokens[0] + " " + tokens[-1]

print("Titles and last names are {}".format(list(map(split_title_and_name, people))))


Titles and last names are ['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']


# Lambdas and list comprehensions

In [50]:
addition = lambda a, b, c: a+b+c
addition(1, 4, 15)

20

In [52]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    tokens = person.split()
    return tokens[0] + " " + tokens[-1]

#option 1
for person in people:
    print("{} {}".format(person.split()[0], person.split()[-1]))
    print(split_title_and_name(person))

#option 2
print(list(map(split_title_and_name, people)) == list(map(lambda person: "{} {}".format(person.split()[0], person.split()[-1]), people)))


Dr. Brooks
Dr. Brooks
Dr. Collins-Thompson
Dr. Collins-Thompson
Dr. Vydiswaran
Dr. Vydiswaran
Dr. Romero
Dr. Romero
True


In [53]:
even_nums = [num for num in range(0, 1000) if num % 2 == 0]
even_nums

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [56]:
def times_tables():
    lst = []
    for i in range(10):
        for j in range (i):
            lst.append(i*j)
    return lst

times_tables() == [i*j for i in range(10) for j in range(i)]

True

In [60]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

answer = ['{}{}{}{}'.format(letter1, letter2, digit1, digit2) for letter1 in lowercase for letter2 in lowercase for digit1 in digits for digit2 in digits]
answer[:220:15]

['aa00',
 'aa15',
 'aa30',
 'aa45',
 'aa60',
 'aa75',
 'aa90',
 'ab05',
 'ab20',
 'ab35',
 'ab50',
 'ab65',
 'ab80',
 'ab95',
 'ac10']

# NumPy

In [61]:
import numpy as np

In [62]:
mylist = [1, 2, "str"]
x = np.array(mylist)
x

array(['1', '2', 'str'], dtype='<U21')

In [64]:
y = np.array([3, 4, 5])
y

array([3, 4, 5])

In [70]:
m = np.array([[7, 8, 9], [10, 11, 12]])
print(m)
m.shape

[[ 7  8  9]
 [10 11 12]]


(2, 3)

In [73]:
n = np.arange(0, 30, 2)
print(n)
n = n.reshape(3,5)
print(n)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]


In [74]:
o = np.linspace(0, 4, 9)
print(o)
o.resize(3,3)
print(o)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ]
[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]


In [76]:
print(np.ones((2, 3)))
print(np.zeros((3, 2)))
print(np.eye(3))
print(np.diag((3, 4)))
print(np.diag(o))

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[3 0]
 [0 4]]
[0. 2. 4.]


In [78]:
print(np.array([1, 2, 3] * 3))
print(np.repeat([1, 2, 3], 3))

[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3]


In [82]:
p = np.ones([2, 3], int)
print(p)
print(np.vstack([p, 2*p]))
print(np.hstack([p, 3*p]))

[[1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]
[[1 1 1 3 3 3]
 [1 1 1 3 3 3]]


## Operations

In [86]:
a = np.array([1, 2, 3])
print(a+y)
print(a*y)
print(a**2)
print(a.dot(y))

[4 6 8]
[ 3  8 15]
[1 4 9]
26


In [87]:
b = [1, 2, 3]
print(a+y)
print(a*y)
# print(a**2) # is not supported
# print(a.dot(y)) # is not supported

[4 6 8]
[ 3  8 15]


In [89]:
z = np.array([y, y**2])
print(z)
print(z.T)

[[ 3  4  5]
 [ 9 16 25]]
[[ 3  9]
 [ 4 16]
 [ 5 25]]


In [91]:
print(z.dtype)
z = z.astype('f')
print(z.dtype)

int64
float32


In [92]:
a = np.array([-4, -2, 1, 3, 5])
print('a.sum() = {}'.format(a.sum()))
print('a.max() = {}'.format(a.max())) 
print('a.min() = {}'.format(a.min()))
print('a.argmax() = {}'.format(a.argmax()))
print('a.argmin() = {}'.format(a.argmin()))
print('a.mean() = {}'.format(a.mean()))
print('a.std() = {}'.format(a.std()))

a.sum() = 3
a.max() = 5
a.min() = -4
a.argmax() = 4
a.argmin() = 0
a.mean() = 0.6
a.std() = 3.2619012860600183


## Indexing / Slicing

In [94]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [98]:
s[0], s[4], s[-3:]

(0, 16, array([100, 121, 144]))

In [99]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [100]:
print(r[3, 3:6])
print(r[:2, :-1])

[21 22 23]
[[ 0  1  2  3  4]
 [ 6  7  8  9 10]]


In [102]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [103]:
r2 = r.copy() # never r2 = r, changes to r2 will change r too
r2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [104]:
test = np.random.randint(0, 10, [4, 3])
test

array([[8, 6, 4],
       [2, 7, 9],
       [1, 2, 1],
       [9, 8, 2]])

In [107]:
for row in test:
    print(row)
    
print()

for i in range(len(test)):
    print(test[i])
    
print()

for i, row in enumerate(test):
    print('row', i, 'is', row)

[8 6 4]
[2 7 9]
[1 2 1]
[9 8 2]

[8 6 4]
[2 7 9]
[1 2 1]
[9 8 2]

row 0 is [8 6 4]
row 1 is [2 7 9]
row 2 is [1 2 1]
row 3 is [9 8 2]


In [108]:
test2 = test ** 2
test2

array([[64, 36, 16],
       [ 4, 49, 81],
       [ 1,  4,  1],
       [81, 64,  4]])

In [109]:
for i, j in zip(test, test2):
    print(i, '+', j, '=', i+j)

[8 6 4] + [64 36 16] = [72 42 20]
[2 7 9] + [ 4 49 81] = [ 6 56 90]
[1 2 1] + [1 4 1] = [2 6 2]
[9 8 2] + [81 64  4] = [90 72  6]
